api_version = "2026-07"

[[extensions]]
name = "t:name"
handle = "no-discount-products"
type = "function"
uid = "0405de6e-2136-707e-c68c-5bbb584a3cdf114c1730"
description = "t:description"

  [[extensions.targeting]]
  target = "cart.validations.generate.run"
  input_query = "src/cart_validations_generate_run.graphql"
  export = "cart-validations-generate-run"

  [extensions.build]
  command = ""
  path = "dist/function.wasm"
